kind: Service
apiVersion: v1
metadata:
  name: mysqldb
  namespace: karmarkar
  labels:
    app: restgosql
spec:
  ports:
    - name: '3306'
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: restgosql
  clusterIP: None
