kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqldb-claim
  labels:
    app: restgosql
  namespace: karmarkar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: mysql-pv
  storageClassName: mysql-database-class
  volumeMode: Filesystem
