apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: karmarkar
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: ashish
      ports:
        - containerPort: 3306
          name: mysql
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: karmarkar
  labels:
    app: mysql-app
    function: frontend
spec:
  containers:
    - name: mysql-app
      image: nivantdot/restgosql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: ashish
      ports:
        - containerPort: 1234
          name: mysql
          protocol: TCP
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: karmarkar
  name: mysql-app-service
spec:
  type: NodePort
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      nodePort: 30005