apiVersion: v1
kind: Resourcequota
metadata:
  name: my-quota
  namespace: karmarkar
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
