apiVersion: v1
kind: Service
metadata:
  labels:
    tier: frontend
  name: myapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: NodePort
status:
  loadBalancer: {}
