apiVersion: v1
kind: Service
metadata:
  namespace: karmarkar
  name: my-sample-service
spec:
  type: NodePort
  selector:
    app: my-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004